#BASE DE DATOS
CREATE DATABASE YOUTUBE1_V2
	DEFAULT CHARACTER SET utf8
	DEFAULT COLLATE utf8_general_ci;

USE YOUTUBE1_V2;

#TABLA CANALES
CREATE TABLE CANALES(
    ID      INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
   	NOMBRE  VARCHAR(40) NOT NULL
    );
 
#TABLA PAISES
CREATE TABLE PAISES(
    ID      INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
   	NOMBRE  VARCHAR(40) NOT NULL
    );

#TABLA LENGUAJES
CREATE TABLE LENGUAJES(
    ID      INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
   	NOMBRE  VARCHAR(40) NOT NULL
    );

#TABLA VIDEOS
CREATE TABLE VIDEOS(
    ID                  VARCHAR(40) PRIMARY KEY,
   	NOMBRE              VARCHAR(40) NOT NULL,
    CANAL_ID            INT(10) UNSIGNED,
    PAIS_ID             INT(10) UNSIGNED,
    LENGUAJE_ID         INT(10) UNSIGNED,
    FECHA_PUBLCACION    DATE NOT NULL,
    FOREIGN KEY (CANAL_ID) 
    REFERENCES CANALES(ID),
    FOREIGN KEY (PAIS_ID) 
    REFERENCES PAISES(ID),
    FOREIGN KEY (LENGUAJE_ID) 
    REFERENCES LENGUAJES(ID)
    );

#TABLA COMENTARIOS
CREATE TABLE COMENTARIOS(
    ID          INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    COMENTARIO  VARCHAR(500),
    VIDEO_ID    VARCHAR(40),
    CANAL_ID    INT(10) UNSIGNED,
    FOREIGN KEY (CANAL_ID) 
    REFERENCES CANALES(ID),
    FOREIGN KEY (VIDEO_ID)
    REFERENCES VIDEOS (ID)
    );